### ISSUE TITLE
Host verification failing due to Google certificate

### ISSUE THREAD

**Issue by hth** [GabiAxel/spring-social-google#67]
Hi,

This piece of code was working couple of months ago. Yesterday, I decided to test it again to confirm if its still working. While testing I got this error. I had not seen this issue couple of months ago. Just want to confirm if this certificate issue is Google's issue and not spring-social-google related. 

Filed bug with Google - https://code.google.com/p/google-apis-explorer/issues/detail?id=300

Thanks
H

    59:27:345 ERROR org.springframework.social.connect.web.ProviderSignInController.oauth2Callback Message=Exception while completing OAuth 2 connection: 
    org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://www.googleapis.com/plus/v1/people/me":Host name 'www.googleapis.com' does not match the certificate subject provided by the peer (CN=*.storage.googleapis.com, O=Google Inc, L=Mountain View, ST=California, C=US); nested exception is javax.net.ssl.SSLPeerUnverifiedException: Host name 'www.googleapis.com' does not match the certificate subject provided by the peer (CN=*.storage.googleapis.com, O=Google Inc, L=Mountain View, ST=California, C=US)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:580)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:530)
        at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:237)
        at org.springframework.social.google.api.impl.AbstractGoogleApiOperations.getEntity(AbstractGoogleApiOperations.java:50)
        at org.springframework.social.google.api.plus.impl.PlusTemplate.getPerson(PlusTemplate.java:105)
        at org.springframework.social.google.api.plus.impl.PlusTemplate.getGoogleProfile(PlusTemplate.java:110)
        at org.springframework.social.google.connect.GoogleAdapter.fetchUserProfile(GoogleAdapter.java:51)
        at org.springframework.social.google.connect.GoogleAdapter.fetchUserProfile(GoogleAdapter.java:31)
        at org.springframework.social.google.connect.GoogleConnectionFactory.extractProviderUserId(GoogleConnectionFactory.java:37)
        at org.springframework.social.connect.support.OAuth2ConnectionFactory.createConnection(OAuth2ConnectionFactory.java:91)
        at org.springframework.social.connect.web.ConnectSupport.completeConnection(ConnectSupport.java:161)
        at org.springframework.social.connect.web.ProviderSignInController.oauth2Callback(ProviderSignInController.java:216)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)

**Comment by GabiAxel** [comment]
Really seems to be on a lower level than Spring Social. Maybe your internal network or proxy is messing with the certificate? Try running it from another location.

**Comment by mlaccetti** [comment]
@hth I ran into the same problem and came up with the following code to fix it: https://gist.github.com/mlaccetti/f824c0bc0b7b2d17084c 

Validated to work, etc.

**Comment by hth** [comment]
@mlaccetti Really appreciate for providing solution. 

Another person has encountered the same issue https://code.google.com/p/google-apis-explorer/issues/detail?id=301.

It would be nice to have this incorporated rather than have it as one-off solution. Thanks again.

**Comment by mlaccetti** [comment]
I'll see if I can integrate the code into the package, if @GabiAxel agrees.

**Comment by oyvindhorneland** [comment]
Since the certificate has these SANs:
DNS Name=*.storage.googleapis.com
DNS Name=*.commondatastorage.googleapis.com
DNS Name=*.googleapis.com
, the certificate should be perfectly valid for www.googleapis.com.

While not the exact same error message, perhaps it's in the same area.. I had issues with spring-social-google after upgrading Apache HttpClient from 4.3 to 4.4. The issue is described in https://issues.apache.org/jira/browse/HTTPCLIENT-1613 "Support for so called 'private' domains in Mozilla Public Suffix List". HttpClient 4.4 cannot be used with spring-social-google.

**Comment by hth** [comment]
@oyvindhorneland Downgrading to 4.3.x solved the issue. Thanks.
